version: '3.3'

services:
    react_app:
        container_name: react_app
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        ports:
            - 8002:8002
        tty: true
        volumes:
            - ./:/var/www

